services:
  portfolio:
    image: node:18-alpine
    container_name: portfolio
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /root/services/portfolio:/app
      - portfolio_node_modules:/app/node_modules
    working_dir: /app
    command: >
      sh -c "yarn install --frozen-lockfile && 
             yarn build &&
             yarn start"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - LOG_LEVEL=debug
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  portfolio_node_modules: