services:
  portfolio:
    image: node:18-alpine
    container_name: portfolio
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /root/services/portfolio:/app
      - portfolio_node_modules:/app/node_modules
    working_dir: /app
    command: >
      sh -c "yarn install  && 
             yarn serve --port 3000"
    environment:
      - NODE_ENV=production

volumes:
  portfolio_node_modules: